### ISSUE TITLE
RecyclerView resizes ExpandableTextViews when another expands

### ISSUE THREAD

**Issue by ccentauri** [KyoSherlock/ExpandableLayout#3]
I us  library to create ExpandableTextView for RecyclerView items, but there is something wrong when I open item and then scroll up - items, which has less then 4 lines (ExpandableTextView expands on >4 lines) become very height.

My screenshots:
[Normal item](http://i.stack.imgur.com/akrPk.png)
[After opening another item and scrolling up to this item](http://i.stack.imgur.com/xqSBi.png)

**Comment by KyoSherlock** [comment]
I can't see your source code, so I create an example with ExpandableTextView, Maybe you can refer to.
