### ISSUE TITLE
The library not work after run proguard

### ISSUE THREAD

**Issue by IHNEL** [KyoSherlock/ExpandableLayout#6]
Hi,
This library stop working if I build my app within proguard. Could you have try please?

**Comment by KyoSherlock** [comment]
Add the following line in the proguard-rules.pro
-keep class com.kyo.expandablelayout.*\* {*;}

**Comment by KyoSherlock** [comment]
I think it's because I used the ObjectAnimator.
mExpandAnimator = ObjectAnimator.ofInt(p, "height", 0, measuredHeight);
So LayoutParam.setHeight should not be obfuscated.

**Comment by IHNEL** [comment]
I add this line `-keep class com.kyo.expandablelayout.** {*;}` into my proguard file and it works like a charm now.

Thank you so much.
